# Generated by Django 4.0.7 on 2023-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
