# Generated by Django 4.1.1 on 2023-09-10 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('exam_date', models.CharField(default='0', max_length=15)),
                ('exam_time', models.CharField(default='0', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Departemant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departemant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='unit_selection.departemant')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=255)),
                ('gender', models.CharField(choices=[('مختلط', 'مختلط'), ('مرد', 'مرد'), ('زن', 'زن')], default='مختلط', max_length=10)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='unit_selection.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='unit_selection.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه')], default='شنبه', max_length=10)),
                ('start', models.CharField(choices=[('8', '8'), ('10', '10'), ('13.5', '13.5'), ('15.5', '15.5'), ('17.5', '17.5')], default='8', max_length=10)),
                ('end', models.CharField(choices=[('9.5', '9.5'), ('11.5', '11.5'), ('15', '15'), ('17', '17'), ('19', '19')], default='9.5', max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='unit_selection.section')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departemant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='unit_selection.departemant')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_pk', models.CharField(max_length=255)),
                ('courses_pk', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='unit_selection.group'),
        ),
    ]
