# Generated by Django 4.1.1 on 2023-09-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_selection', '0003_favourite_sections_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه')], default='شنبه', max_length=10),
        ),
    ]
